import sys

try:
    with open('src/kafka_to_postgres.py', 'r', encoding='utf-8') as f:
        content = f.read()

    repl1_old = """from shared_constants import (
    CIRCUIT_BREAKER_RESET_SECS,
    CIRCUIT_BREAKER_THRESHOLD,
    CONSUMER_DB_BACKOFF_SECS,
    CONSUMER_DB_SLOW_MS,
    ALERT_ACK_COOLDOWN_MINUTES,
    ALERT_RULE_LOOKBACK_MINUTES,
    DATA_RETENTION_DAYS,
    DB_INSERT_BATCH_SIZE,
    EVENT_PARTITIONING_ENABLED,
    EVENT_PARTITION_MONTHS_AHEAD,
    EVENT_PARTITION_MONTHS_BEHIND,
    KAFKA_BOOTSTRAP_SERVERS,
    KAFKA_CONSUMER_CLIENT_ID,
    KAFKA_GROUP_ID,
    KAFKA_LAG_LOG_INTERVAL_SECS,
    KAFKA_LAG_WARNING_THRESHOLD,
    KAFKA_MAX_POLL_RECORDS,
    KAFKA_MIN_TOPIC_PARTITIONS,
    KAFKA_POLL_TIMEOUT_MS,
    KAFKA_TOPIC,
    KAFKA_TOPIC_REPLICATION_FACTOR,
    RAW_XML_MAX_BYTES,
    RETENTION_CLEANUP_ENABLED,
    RETENTION_CLEANUP_INTERVAL_SECS,
    RETENTION_DELETE_BATCH_SIZE,
    COLLECTOR_SECRET,
)"""

    repl1_new = """from shared.resilience_constants import (
    CIRCUIT_BREAKER_RESET_SECS,
    CIRCUIT_BREAKER_THRESHOLD,
)
from shared.kafka_constants import (
    CONSUMER_DB_BACKOFF_SECS,
    CONSUMER_DB_SLOW_MS,
    KAFKA_BOOTSTRAP_SERVERS,
    KAFKA_CONSUMER_CLIENT_ID,
    KAFKA_GROUP_ID,
    KAFKA_LAG_LOG_INTERVAL_SECS,
    KAFKA_LAG_WARNING_THRESHOLD,
    KAFKA_MAX_POLL_RECORDS,
    KAFKA_MIN_TOPIC_PARTITIONS,
    KAFKA_POLL_TIMEOUT_MS,
    KAFKA_TOPIC,
    KAFKA_TOPIC_REPLICATION_FACTOR,
)
from shared.api_constants import (
    ALERT_ACK_COOLDOWN_MINUTES,
    ALERT_RULE_LOOKBACK_MINUTES,
)
from shared.db_constants import (
    DATA_RETENTION_DAYS,
    DB_INSERT_BATCH_SIZE,
    EVENT_PARTITIONING_ENABLED,
    EVENT_PARTITION_MONTHS_AHEAD,
    EVENT_PARTITION_MONTHS_BEHIND,
    RAW_XML_MAX_BYTES,
    RETENTION_CLEANUP_ENABLED,
    RETENTION_CLEANUP_INTERVAL_SECS,
    RETENTION_DELETE_BATCH_SIZE,
)
from shared.collector_constants import (
    COLLECTOR_SECRET,
)"""

    content = content.replace(repl1_old, repl1_new)

    with open('src/kafka_to_postgres.py', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Success")
except Exception as e:
    print("Error:", e)
