import os
from shared.system_constants import env_int, env_float

KAFKA_BOOTSTRAP_SERVERS = (
    os.getenv("SENTINEL_KAFKA_BROKERS")
    or os.getenv("SENTINEL_KAFKA_HOST")
    or os.getenv("KAFKA_BOOTSTRAP")
    or "localhost:9092"
)
KAFKA_TOPIC = os.getenv("SENTINEL_KAFKA_TOPIC", "sentinel-events")
KAFKA_GROUP_ID = os.getenv("SENTINEL_KAFKA_GROUP_ID", "postgres-ingester-group")
KAFKA_CONSUMER_CLIENT_ID = os.getenv("SENTINEL_KAFKA_CONSUMER_CLIENT_ID", "sentinel-consumer")
KAFKA_POLL_TIMEOUT_MS = env_int("SENTINEL_KAFKA_POLL_TIMEOUT_MS", 5000)
KAFKA_MAX_POLL_RECORDS = env_int("SENTINEL_KAFKA_MAX_POLL_RECORDS", 50)
KAFKA_MIN_TOPIC_PARTITIONS = env_int("SENTINEL_KAFKA_MIN_TOPIC_PARTITIONS", 3)
KAFKA_TOPIC_REPLICATION_FACTOR = env_int("SENTINEL_KAFKA_TOPIC_REPLICATION_FACTOR", 1)
KAFKA_LAG_LOG_INTERVAL_SECS = env_int("SENTINEL_KAFKA_LAG_LOG_INTERVAL_SECS", 30)
KAFKA_LAG_WARNING_THRESHOLD = env_int("SENTINEL_KAFKA_LAG_WARNING_THRESHOLD", 250)

# Stability tuning configs
KAFKA_ENABLE_IDEMPOTENCE = True
KAFKA_ACKS = 'all'
KAFKA_RETRIES = 5
KAFKA_LINGER_MS = 10

CONSUMER_DB_SLOW_MS = env_int("SENTINEL_CONSUMER_DB_SLOW_MS", 1500)
CONSUMER_DB_BACKOFF_SECS = env_float("SENTINEL_CONSUMER_DB_BACKOFF_SECS", 2.0)
