from shared.system_constants import env_int

CPU_ALERT_THRESHOLD = env_int("SENTINEL_CPU_ALERT_THRESHOLD", 90)
MEMORY_ALERT_THRESHOLD = env_int("SENTINEL_MEMORY_ALERT_THRESHOLD", 90)
DISK_LOW_THRESHOLD = env_int("SENTINEL_DISK_LOW_THRESHOLD", 10)

FEATURE_BUILDER_INTERVAL_SECS = env_int("SENTINEL_FEATURE_BUILDER_INTERVAL_SECS", 30)
FEATURE_BUILDER_LOOKBACK_SECS = env_int("SENTINEL_FEATURE_BUILDER_LOOKBACK_SECS", 30)
FEATURE_BUILDER_HARD_TIMEOUT_SECS = env_int("SENTINEL_FEATURE_BUILDER_HARD_TIMEOUT_SECS", 25)
FEATURE_BUILDER_BATCH_TIMEOUT_SECS = env_int("SENTINEL_FEATURE_BUILDER_BATCH_TIMEOUT_SECS", 10)
FEATURE_BUILDER_THREAD_WORKERS = env_int("SENTINEL_FEATURE_BUILDER_THREADS", 4)
FEATURE_BUILDER_SYSTEM_BATCH_SIZE = env_int("SENTINEL_FEATURE_BUILDER_SYSTEM_BATCH_SIZE", 25)
