from shared.system_constants import env_int, env_float

RETRY_MAX_ATTEMPTS = env_int("SENTINEL_RETRY_MAX_ATTEMPTS", 3)
RETRY_BACKOFF_SECONDS = env_float("SENTINEL_RETRY_BACKOFF_SECONDS", 2.0)
DB_QUERY_TIMEOUT_SECONDS = env_int("SENTINEL_DB_QUERY_TIMEOUT_SECONDS", 5)
API_RESPONSE_TIMEOUT_SECONDS = env_int("SENTINEL_API_RESPONSE_TIMEOUT_SECONDS", 3)
CIRCUIT_BREAKER_THRESHOLD = env_int("SENTINEL_CIRCUIT_BREAKER_THRESHOLD", 5)
CIRCUIT_BREAKER_RESET_SECS = env_float("SENTINEL_CIRCUIT_BREAKER_RESET_SECS", 30.0)
